opensearch-project/opensearch-prometheus-exporter

README.md
gradle.properties

Closes #13
Signed-off-by: lukas-vlcek <lukas.vlcek@aiven.io>

Upgrade to OpenSearch 1.2.4

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

We selected [Contributor Covenant CoC](https://www.contributor-covenant.org/).

Specify Code of Conduct

---

CONTRIBUTING.md

See upstream PR: https://github.com/opensearch-project/opensearch-plugin-template-java/pull/26

Fixing LICENSE link

---

CONTRIBUTING.md
SECURITY.md

Specify Security Policy

---

.github/workflows/CI.yml
.github/workflows/dco.yml

Starting with a minimal set of perms required.

Set GitHub action permissions

---

README.md

Prepare URL link and compatibility matrix for upcoming release.

Prepare README for new release

---

gradle.properties

Upgrade to OpenSearch 1.3.0

---

README.md

Release 1.3.0.0

---

gradle.properties

Upgrade to OpenSearch 1.3.1

---

README.md

Release 1.3.1.0

---

gradle.properties

https://github.com/opensearch-project/OpenSearch/releases/tag/1.3.2
https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-1.3.2.md

Upgrade to OpenSearch 1.3.2

---

README.md

Release 1.3.2.0

---

README.md

Release 2.0.0.0

---

gradle.properties

Upgrade to OpenSearch 1.3.3

---

README.md

Release 1.3.3.3

---

README.md

Add link to OpenSearch Node filters docs

---

gradle.properties

plugin version bump to 2.0.1.0 to create compatibility with opensearch version 2.0.1

Upgrade to OpenSearch 2.0.1

---

README.md

Release 2.1.0.0

---

RELEASE_PROCESS.md

Document the release process

---

RELEASE_PROCESS.md

- Add chapter links
- Formatting

Improve release process doc

---

gradle.properties

Signed-off-by: Victor Nilsson <victor.nilsson@etraveligroup.com>

Bumped the exporter to support version 2.2.0

---

README.md

Release 2.2.0.0

---

README.md
gradle.properties

https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-1.3.5.md

chore: bump OpenSearch from 1.3.4 to 1.3.5

---

README.md

Release 1.3.5.0

---

src/main/java/org/opensearch/action/NodePrometheusMetricsRequest.java

Fix deprecation warnings

---

README.md
gradle.properties

https://github.com/opensearch-project/opensearch-build/releases/tag/2.3.0
https://github.com/opensearch-project/OpenSearch/blob/main/release-notes/opensearch.release-notes-2.3.0.md

chore: bump OpenSearch from 2.2.1 to 2.3.0

---

README.md

Release 2.3.0.0

---

src/main/java/org/compuscene/metrics/prometheus/PrometheusMetricsCatalog.java
src/main/java/org/compuscene/metrics/prometheus/PrometheusMetricsCollector.java
src/main/java/org/compuscene/metrics/prometheus/PrometheusSettings.java
src/main/java/org/opensearch/action/ClusterStatsData.java
src/main/java/org/opensearch/action/NodePrometheusMetricsAction.java
src/main/java/org/opensearch/action/NodePrometheusMetricsRequest.java
src/main/java/org/opensearch/action/NodePrometheusMetricsResponse.java
src/main/java/org/opensearch/action/TransportNodePrometheusMetricsAction.java
src/main/java/org/opensearch/plugin/prometheus/PrometheusExporterPlugin.java
src/main/java/org/opensearch/plugin/prometheus/RenamePlugin.java
src/main/java/org/opensearch/rest/prometheus/RestPrometheusMetricsAction.java

Add missing JAVADOC

---

README.md

Release 2.4.0.0

---

RELEASING.md

Add release steps doc

---

Makefile

Add target to refresh jb dependencies

---

gradle.properties

Signed-off-by: Victor Nilsson <victor.nilsson@etraveligroup.com>

Upgrade exporter to 2.4.1.0

---

README.md
gradle.properties

Signed-off-by: Stein Arne Storslett <sastorsl@users.noreply.github.com>
https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-1.3.7.md

Upgrade to OpenSearch 1.3.7

---

README.md

Release 1.3.7.0

---

README.md

Release 2.4.1.0

---

gradle.properties

Signed-off-by: Victor Nilsson <victor.nilsson@etraveligroup.com>

Upgrade to OpenSearch 2.5.0

---

build.gradle

Specify REST API specs for yamlRestTest

---

README.md

Release 2.5.0.0

---

gradle.properties

Bump the exporter to support 2.6.0

Upgrade the exporter to support OpenSearch 2.6.0

---

README.md

Update Compatibility Matrix

---

.github/ISSUE_TEMPLATE/new-release.md

A new custom template for new releases.

Adding a new custom issue template

---

gradle.properties

This PR prepares the plugin for use with OpenSearch 2.8.0

[#184] upgrade to OpenSearch 2.8.0

---

gradle.properties

Upgrade to OpenSearch 1.3.11

---

CONTRIBUTING.md

Fix a long form DCO commit example

---

gradle.properties
src/main/java/org/compuscene/metrics/prometheus/PrometheusMetricsCollector.java
src/main/java/org/compuscene/metrics/prometheus/PrometheusSettings.java

Upgrading OpenSearch to `2.9.0`. This PR surpasses https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/pull/203.
Closes #203 
---

Upgrade to OpenSearch 2.9.0

---

README.md

The `2.9.0.0` release commit.
---

Release 2.9.0.0

---

gradle.properties

Upgrade to OpenSearch 1.3.12

---

README.md

Creating a release commit according to [Release Process](https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/blob/2434625488a8a2e730518a97be9b1a320b0b0b68/RELEASE_PROCESS.md#3-create-and-push-the-release-commit).
---

Release 1.3.12.0

---

gradle.properties

Upgrading to OpenSearch 1.3.13
---

Upgrade to OpenSearch 1.3.13

---

README.md

A commit for new `1.3.13.0` release.
---

Release 1.3.13.0

---

README.md

Sync. Support Matrix with v1.3 branch

---

README.md

Release 2.10.0.0

---

README.md

Release 2.11.0.0

---

README.md

Release 2.11.1.0

---

gradle.properties

Upgrade to OpenSearch 1.3.14.
---

Upgrade to OpenSearch 1.3.14

---

README.md

Release 1.3.14.0

---

README.md

Sync README file with `v1.3` branch due to `1.3.14.0` release.
---

Sync Compatibility Matrix with v1.3 branch

---

README.md

Release 2.12.0.0

---

gradle.properties

Upgrade to OpenSearch 1.3.15
---

Upgrade to OpenSearch 1.3.15

---

README.md

The release commit for #259
---

Release 1.3.15.0

---

gradle.properties

Upgrade to OpenSearch 2.13.0
---

Upgrade to OpenSearch 2.13.0

---

README.md

Release 2.13.0.0

---

README.md

Release 2.14.0.0

---

gradle.properties

Upgrade to OpenSearch 1.3.16
---

Upgrade to OpenSearch 1.3.16

---

README.md

Update compatibility matrix after new 1.x release has been cut.
---

Update compatibility matrix for 1.3.x

---

README.md

Release 2.15.0.0

---

gradle.properties

Upgrade to OpenSearch 1.3.17
---

Upgrade to OpenSearch 1.3.17

---

README.md

Release 1.3.17.0

---

README.md

Add release `1.3.17.0`:
https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/issues/279
---

Sync releases with `v1.3` branch

---

README.md

Release 2.16.0.0

---

gradle.properties

Upgrade to OpenSearch 1.3.18.0

---

README.md

Release 1.3.18.0

---

gradle.properties

Upgrade to OpenSearch 1.3.19.
---

Upgrade to OpenSearch 1.3.19

---

README.md

Release 1.3.19.0

---

README.md

Release 2.17.0.0

---

README.md

Release 2.17.1.0

---

README.md

Fix 2.18.0.0 release date in compatibility matrix

Fix 2.18.0.0 release date

---

gradle.properties
src/test/java/org/opensearch/plugin/bwc/PluginBackwardsCompatibilityIT.java

Upgrade OpenSearch to 2.19.0 and update BWC tests
#346 

Upgrade opensearch to 2.19.0

---

gradle.properties
src/test/java/org/opensearch/plugin/bwc/PluginBackwardsCompatibilityIT.java

Upgrade OpenSearch to 2.19.1 and update BWC tests

Upgrade OpenSearch to 2.19.1

---

README.md

Update compatibility matrix and installation command for 2.19.1.0 release

Release 2.19.1.0

---

README.md

Update compatibility matrix and installation command for 2.19.2.0 release
#363 

Release 2.19.2.0

---

gradle.properties
src/test/java/org/opensearch/plugin/bwc/PluginBackwardsCompatibilityIT.java

Upgrade to opensearch 2.19.3

---

README.md

Update compatibility matrix and installation command for 2.19.3.0 release
#366 

Release 2.19.3.0

---

COMPATIBILITY.md
README.md

- Update compatibility matrix and installation command for 3.1.0.0 release
- Move compatibility matrix to another file and link from README
#373 

Release 3.1.0.0
