opensearch-project/opensearch-prometheus-exporter

- README.md
- src/yamlRestTest/resources/rest-api-spec/test/20_11_index_level_metrics_disabled.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_00_index_level_info.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_10_index_indexing.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_11_index_get.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_12_index_search.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_13_index_merges.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_14_index_refresh.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_15_index_flush.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_16_index_querycache.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_17_index_fieldata.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_18_index_completion.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_19_index_segments.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_20_index_suggest.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_21_index_requestcache.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_22_index_recovery.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_23_index_translog.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_24_index_warmer.yml
- Remove use of index types in tests (it was yielding deprecation warning)
- Fix instructions about running individual IT tests
Closes #1
Closes #3
Signed-off-by: lukas-vlcek <lukas.vlcek@aiven.io>
> Make integration tests not use index types

- README.md
- src/main/java/org/compuscene/metrics/prometheus/PrometheusSettings.java
- src/main/java/org/opensearch/plugin/prometheus/PrometheusExporterPlugin.java
- src/main/java/org/opensearch/rest/prometheus/RestPrometheusMetricsAction.java
- src/yamlRestTest/resources/rest-api-spec/test/20_00_metrics.yml
- src/yamlRestTest/resources/rest-api-spec/test/20_10_cluster_settings_metrics_disabled.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_00_index_level_info.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_10_index_indexing.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_11_index_get.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_12_index_search.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_13_index_merges.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_14_index_refresh.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_15_index_flush.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_16_index_querycache.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_17_index_fieldata.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_18_index_completion.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_19_index_segments.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_20_index_suggest.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_21_index_requestcache.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_22_index_recovery.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_23_index_translog.yml
- src/yamlRestTest/resources/rest-api-spec/test/30_24_index_warmer.yml
- src/yamlRestTest/resources/rest-api-spec/test/40_10_cluster_settings_disk_threshold.yml
- src/yamlRestTest/resources/rest-api-spec/test/40_20_cluster_settings_disk_watermark_bytes.yml
Introducing a new setting `prometheus.metric_name.prefix` with the default value `opensearch_`.
Closes #7
Signed-off-by: lukas-vlcek <lukas.vlcek@aiven.io>
> Make the metric name prefix configurable

- README.md
Making sure we attribute all trademarks owned by respective owners.
> Trademarks and Attributions cleansing

- build.gradle
This commit introduces support for release candidate builds.
This means we can now build and publish plugin releases for OpenSearch-rc releases.
More specifically, we now support the following plugin versioning schemas:
**Release candidates schema: A.B.C.D-rcE**
Examples:
Plugin ver.         Required OpenSearch ver.
-----------------   -----------------
1.0.0.1-rc2         1.0.0-rc2
2.10.4.0-rc5        2.10.4-rc5
Regular (and legacy) schema: A.B.C.D[-SNAPSHOT]
Examples:
Plugin ver.         Required OpenSearch ver.
-----------------   -----------------
1.0.0.1             1.0.0
2.10.4.0-SNAPSHOT   2.10.4
If the plugin version does not follow supported schemas then an exception is thrown and build process is terminated.
Closes: #51
> Support for rc builds

- build.gradle
- gradle.properties
https://opensearch.org/blog/releases/2022/05/opensearch-2-0-is-now-available/
> Upgrade to OpenSearch 2.0.0

- README.md
i first wanted to contribute the actual version upgrade just to realise that this is all handled just based on the version number :)
so i thought i'd at least provide the README update.
i briefly tested that this compiles fine (& the tests run through):
```
$ ./gradlew build -Pversion=2.0.1.0
> Configure project :
Identifing version of OpenSearch based on plugin version
- OpenSearch version: 2.0.1
- Prometheus exporter plugin version: 2.0.1.0
=======================================
OpenSearch Build Hamster says Hello!
Gradle Version        : 6.8.3
OS Info               : Windows 10 10.0 (amd64)
JDK Version           : 11 (Eclipse Adoptium JDK)
JAVA_HOME             : [..]
Random Testing Seed   : F83F4696E46B3A26
In FIPS 140 mode      : false
=======================================
BUILD …
```
> prepare release v2.0.1.0 for OpenSearch 2.0.1

- README.md
- gradle.properties
https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.2.1.md
> chore: bump OpenSearch from 2.2.0 to 2.2.1

- README.md
- gradle.properties
https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-1.3.6.md
> chore: bump OpenSearch from 1.3.5 to 1.3.6

- README.md
Explain that starting now we maintain two branches in this repository. One for the plugin (the `main` branch) and one for the jsonnet bundle (the `mixin` branch).
> Add Preambule

- build.gradle
Removing OpenSearch plugin template leftover from `build.gradle`.
See: #9
> Remove leftover from plugin template

- src/main/plugin-metadata/plugin-security.policy
We do not need any grants in `plugin-security.policy`. There is currently no PrivilegedAction block. Removal of grants simplify plugin installation a bit because no user confirmation is needed any longer.
This is not a breaking change because when plugins are installed from script then usually `-b` option is used anyway, which skips the confirmation step.
Closes: #131
> Remove all grants from `plugin-security.policy`

- .github/dependabot.yml
this will (partially) automate dependency updates. dependabot will create PRs if a dependency can be updated automatically. see the [dependabot documentation][docs] for further information.
solves #149
note: as always with dependabot config there isn't any easy way to test this, so this is untested (it's actually the first time i'm setting it up for a gradle project! with other projects it worked fine so far).
[docs]: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
> enable GitHub dependabot

- README.md
- build.gradle
- config/checkstyle/checkstyle.xml
- src/main/java/org/compuscene/metrics/prometheus/PrometheusSettings.java
- src/main/java/org/opensearch/action/TransportNodePrometheusMetricsAction.java
- src/main/java/org/opensearch/plugin/prometheus/PrometheusExporterPlugin.java
- src/yamlRestTest/resources/rest-api-spec/test/50_10_nodes_filter.yml
- src/yamlRestTest/resources/rest-api-spec/test/60_10_indices_filter.yml
This addresses the issue https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/issues/166
> Introduce indices filter

- gradle.properties
OpenSearch 2.7.0 is set to release tomorrow, 25/4-2023. This pre-release PR is added to quickly push out a new version of the prometheus-exporter whenever 2.7.0 is released.
> Pre-upgrade the exporter to support OpenSearch 2.7.0

- README.md
Update README.md to clarify plugin/opensearch version sync
See NOTE: under Compatibility Matrix
As requested by @lukas-vlcek in https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/issues/197
New commit w/ DCO and new PR - superseding #198 w/ some discussion.
---
> Update README.md to clarify plugin/opensearch version sync

- .github/workflows/dco.yml
Switching from <https://github.com/tim-actions/dco> to <https://github.com/tisonkun/actions-dco>. While both implementations look very similar there are some differences:
- The later implementation does not require use of additional action to pull PR commits because it does not rely on `commits` being setup in `core` context.
- The later implementation is explicit about its LICENSE (AL2).
---
> Use different DCO action implementation

- gradle.properties
Upgrade the exporter to support OpenSearch 2.11.0
---
> Upgrade the exporter to support OpenSearch 2.11.0

- gradle.properties
> Upgrade exporter version to 2.11.1.0

- README.md
Following #253 we need to update JDK version in documentation as well.
---
> Doc: Update JDK version for testing

- .github/workflows/CI.yml
- gradle.properties
> Upgrade the exporter to support OpenSearch 2.12.0

- gradle.properties
Bump the version to match the current release of OpenSearch 2.14.0
---
> Bump exporter to version 2.14.0

- README.md
> Release 1.3.16.0

- gradle.properties
Upgrade the exporter to support OpenSearch 2.15.0
---
> Upgrade to OpenSearch 2.15.0

- gradle.properties
Bump the exporter to support OpenSearch 2.16
---
> Bump the exporter to support OpenSearch 2.16

- gradle.properties
Upgrade exporter to be compatible with OpenSearch 2.17.0
---
> Upgrade exporter to be compatible with OpenSearch 2.17.0

- gradle.properties
Upgrade exporter to be compatible with OpenSearch 2.17.1
---
> Upgrade exporter to be compatible with OpenSearch 2.17.1

- README.md
Updating some broken links to opensearch docs
---
> Update broken links to opensearch docs in README.md

- README.md
Add default value in documentation for `prometheus.cluster.settings`
Closes https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/issues/297
---
> Add default value for prometheus.cluster.settings

- .github/workflows/BWC.yml
- .gitignore
- README.md
- build.gradle
- bwctest.sh
- gradle.properties
- src/test/java/org/opensearch/plugin/bwc/PluginBackwardsCompatibilityIT.java
This commit introduces necessary changes to enable BWC testing.
Closes: #315
---
> Introduce BWC testing infrastructure

- build.gradle
- gradle.properties
In order to remove hardcoded version of actual OpenSearch from BWC versions array we need to introduce new 'empty' property and update it before testClusters are defined.
Closes: #324
---
> BWC testing: remove hardcoded OpenSearch version

- .github/CODEOWNERS
- .github/pull_request_template.md
- .github/workflows/add-untriaged.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- MAINTAINERS.md
- NOTICE.txt
- SECURITY.md
- Add MAINTAINERS.md and update CODEOWNERS
- Update files to match OpenSearch contents:
- SECURITY.md
- NOTICE.txt
- CODE_OF_CONDUCT.md
- pull_request_template.md
- Add `add-untriaged` github workflow
We are working with LF to add @sam-herman as a maintainer to the repo, will add to codeowners in a follow-up PR
Related issue: #346 
---
> Update doc files to match OpenSearch

- gradle.properties
- src/test/java/org/opensearch/plugin/bwc/PluginBackwardsCompatibilityIT.java
Upgrade OpenSearch to 2.19.2 and update BWC tests
> Upgrade OpenSearch to 2.19.2
